### ISSUE TITLE
Allow passing server uri to constructor

### ISSUE THREAD

**Issue by autarch** [jhthorsen/openapi-client#14]
It'd be really nice to support passing the server's URI to the constructor. As it stands it's pretty challenging to use this code against a test server running locally. I have to munge the swagger file to inject the proper `host` into it.

**Comment by autarch** [comment]
Then I realized this already works. Oops.

**Comment by jhthorsen** [comment]
Does this mean that the documentation need some improvement?

**Comment by autarch** [comment]
I think some doc improvements couldn't hurt. This is covered in a section entitled "Customization", which isn't a great title. I think it'd also be nice if you could just pass this to the constructor.

**Comment by jhthorsen** [comment]
What do you think about the change in 09c80ed?

**Comment by autarch** [comment]
That's not bad, but I think an explicit section on the constructor and the options it can accept would also be useful.

**Comment by jhthorsen** [comment]
I welcome a PR or a snippet in this issue about how to make it better!
