### ISSUE TITLE
Deprecation-warnings for `JSON::Validator->coerce(1)`

### ISSUE THREAD

**Issue by christopherraa** [jhthorsen/openapi-client#17]
Are there any plans for what to do in this module now that  `JSON::Validator->coerce(1)` is marked for deprecation? It is used [here](https://github.com/jhthorsen/openapi-client/blob/f321ec4464b5ccc7258e293b8f92b0adfb8617d6/lib/OpenAPI/Client.pm#L48) and marked for deprecation [here](https://github.com/mojolicious/json-validator/blob/a2464cf95807d2df59db2683b3955e1a0ac7736c/lib/JSON/Validator.pm#L135).

**Comment by jhthorsen** [comment]
The plan is to fix it 😄

I got a new version ready, but waiting for https://pause.perl.org/pause/authenquery to stop reporting "Internal Server Error" 😞
