### ISSUE TITLE
Header parameter example

### ISSUE THREAD

**Issue by ravenhall** [jhthorsen/openapi-client#21]
The docs could really use an example of a header parameter when making an OpenAPI call.

**Comment by jhthorsen** [comment]
I'm not sure how to do that, without making a lot of different examples. The documentation states:

> $params is optional, but must be a hash ref, where the keys should match a named parameter in the OpenAPI specification.

I thought that would read as any of the named parameters can be passed in, no matter if it's body, header, path or query. Can you help me make that more obvious?

**Comment by jhthorsen** [comment]
I'm closing this issue based on inactivity.

**Comment by XSven** [comment]
Replace the example

`$tx = $client->listPets({limit => 10});`

with

`$tx = $client->listPets({"X-API-Key" => "abcdef12345", limit => 10});`

That's it.
