### ISSUE TITLE
t/command-local-with-ref.t fails with Mojolicious::Plugin::API@2.16

### ISSUE THREAD

**Issue by glauschwuffel** [jhthorsen/openapi-client#23]
Hi,

t/command-local-with-ref.t fails with Mojolicious::Plugin::API@2.16.

https://www.cpantesters.org/cpan/report/51c6c38a-c3e0-11e9-a97d-ebc033f4362a

I'm opening this ticket because this information unluckily can't be seen from the test report.

**Comment by kiwiroy** [comment]
duplicate of #22
