### ISSUE TITLE
Return rejected Promise rather than croak.

### ISSUE THREAD

**Issue by kiwiroy** [jhthorsen/openapi-client#24]
Would it be better to return a rejected `Mojo::Promise` rather than `Carp::croak` in `call_p`?

https://github.com/jhthorsen/openapi-client/blob/5b53b799a53712ecea77325aea144c19432550d4/lib/OpenAPI/Client.pm#L37-L41

Changing to this.
```perl
my $code = $self->can("${op}_p")
    or return Mojo::Promise->new->reject("[OpenAPI::Client] No such operationId");
```

Allows the usual
```perl
$api->call_p('incorrect?')->then(sub { ... }, sub { $error = shift; })->wait;
```

**Comment by mohawk2** [comment]
This sounds to me like it would be far more idiomatic.

**Comment by jhthorsen** [comment]
Closing this in favor of #25.
