### ISSUE TITLE
OpenAPI 3 support

### ISSUE THREAD

**Issue by yoe** [jhthorsen/openapi-client#29]
Looks like OpenAPI::Client doesn't currently support OpenAPI 3. Would be cool if it did, because Mojolicious::Plugin::OpenAPI does, and it's a one-way conversion... which means my Grand Plan(tm) of autogenerating the client-side API for the OpenAPI thing won't work :-/

Would this be very complicated?

**Comment by jhthorsen** [comment]
This have unfortunately been postponed, since *life* came in the way. I want to finish https://github.com/mojolicious/json-validator/compare/jhthorsen/openapi first, since I think that will make it very easy to implement v3 support. That is also the reason why I haven't taken #27.

**Comment by yoe** [comment]
Oh, I missed #27. Sorry, ignore me, nothing to see here :-)

**Comment by reneeb** [comment]
@jhthorsen Anything we can do to help?
