### ISSUE TITLE
OpenAPI::Client rejecting schema accepted by Swagger2::Client

### ISSUE THREAD

**Issue by gquipster** [jhthorsen/openapi-client#6]
Hi,

Atempting to load schema results in error of:

Invalid JSON specification HASH(0x11c7348):
- /securityDefinitions/myIdentity: oneOf failed: Properties not allowed: authorizationUrl, flow, scopes, tokenUrl. Properties not allowed: authorizationUrl, flow, scopes, tokenUrl. Properties not allowed: tokenUrl. Properties not allowed: authorizationUrl. Properties not allowed: authorizationUrl. Not in enum list: accessCode. at /usr/local/share/perl/5.18.2/JSON/Validator.pm line 157.

securityDefinitions in API schema looks like:

```
  "securityDefinitions": {
    "myIdentity": {
      "flow": "implicit",
      "authorizationUrl": "https://identity.server.local/connect/authorize",
      "tokenUrl": "https://identity.server.local/connect/token",
      "scopes": {
        "myAPI": "The scope needed to access the API"
      },
      "type": "oauth2",
      "description": "My Identity Implicit Grant"
    }
  }
```

This worked with the Swagger2::Client.

Thanks

**Comment by jhthorsen** [comment]
Hi. Sorry for the late response...

It does not seem like `tokenUrl` can be present when `flow` is "implicit". The schema is valid if you either remove `tokenUrl` or change `flow` to "accessCode".

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#securitySchemeObject
